services:
  # Versão completa com suporte a crewai e IA
  python-app:
    build:
      context: .
    container_name: python-app
    restart: unless-stopped
    init: true
    # Expose Streamlit's default port as per Dockerfile and README
    ports:
      - "8501:8501"
    
    env_file: ./.env 
    volumes:
      - ./data:/app/data
      - ./group_summary.csv:/app/group_summary.csv
    profiles:
      - full

  # Versão leve sem crewai (imagem 78% menor)
  python-app-slim:
    build:
      context: .
      dockerfile: Dockerfile.lite
    container_name: python-app-slim
    restart: unless-stopped
    init: true
    ports:
      - "8501:8501"
    
    env_file: ./.env
    volumes:
      - ./data:/app/data
      - ./group_summary.csv:/app/group_summary.csv
    profiles:
      - slim

# No external services (databases, caches, brokers, etc.) were detected in the README or Dockerfile.
# No volumes section is included as there are no persistent data requirements.
# Only the Streamlit port (8501) is exposed as per Dockerfile and README instructions.
