services:
  app:
    build: .
    container_name: groups-evo-crewai
    env_file:
      - .env # Carrega variáveis do arquivo .env
    ports:
      - "8501:8501"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Lisbon  # Configura fuso horário de Portugal
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Sincroniza com horário do sistema host
      - /etc/timezone:/etc/timezone:ro    # Sincroniza timezone do sistema host
