services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile_simple
    container_name: groups-evo-crewai-simple
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Lisbon
      - DOCKER_ENV=true
    volumes:
      - ./data:/app/data
