services:
  app:
    image: groups-evo-crewai:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: groups-evo-crewai
    env_file:
      - .env # Carrega variáveis do arquivo .env
    ports:
      - "8502:8501"
    restart: unless-stopped
