version: '3'

services:
  whatsapp-summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-summarizer
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge
