version: "3.12"
services:
  app:
    build: .
    container_name: groups-evo-crewai
    env_file:
      - .env # Carrega variáveis do arquivo .env
    ports:
      - "8501:8501"
    restart: unless-stopped
